name: Update Develop
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - uses: pulumi/actions@v4
        with:
          cloud-url: s3://garunski-scry-pulumi-state-backend/dev?endpoint=nyc3.digitaloceanspaces.com
          command: up
          stack-name: develop
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          AWS_REGION: 'us-east-1'
          PULUMI_CONFIG_PASSPHRASE: ''